/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

/**
 *
 * @author Windows 10
 */
public class Estadisticas extends javax.swing.JFrame {

    /**
     * Creates new form Estadisticas
     */
    public Estadisticas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, -1, -1));

        jButton2.setText("Cargar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 670, -1, -1));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, 80, 20));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, 80, 20));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, 80, 20));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 315, 80, 20));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 425, 80, 20));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 465, 80, 20));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 505, 80, 20));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 550, 80, 20));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 595, 80, 20));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 635, 80, 20));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 675, 80, 20));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 80, 20));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 80, 20));
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 80, 20));
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 315, 80, 20));
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 425, 80, 20));
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 465, 80, 20));
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 505, 80, 20));
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, 80, 20));
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 595, 80, 20));
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 635, 80, 20));
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 675, 80, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Estadisticas.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1000, 730));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1040, 700));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu newframe = new Menu();
        
        newframe.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       try {
        BufferedReader reader = new BufferedReader(new FileReader("Datos Apple.txt"));
        String line;
        while ((line = reader.readLine()) != null) {
            String[] partes = line.split("=");
            if (partes[0].equals("Utilidad Apple")) {
                String utilidadApple = String.valueOf(partes[1]);
                jLabel13.setText(utilidadApple);
            } else if (partes[0].equals("Costo Operativo Apple")) {
                String costoApple = String.valueOf(partes[1]);
                jLabel14.setText(costoApple);
            } else if (partes[0].equals("Ganancias Brutas Apple")) {
                String gananciasApple = String.valueOf(partes[1]);
                jLabel15.setText(gananciasApple);
            } else if (partes[0].equals("Multas PM Apple")) {
                String multaApple = String.valueOf(partes[1]);
                jLabel16.setText(multaApple);
            } else if (partes[0].equals("CPU Apple")) {
                String cpuApple = String.valueOf(partes[1]);
                jLabel17.setText(cpuApple);
            } else if (partes[0].equals("Placas Apple")) {
                String placasApple = String.valueOf(partes[1]);
                jLabel18.setText(placasApple);
            } else if (partes[0].equals("RAM Apple")) {
                String ramApple = String.valueOf(partes[1]);
                jLabel19.setText(ramApple);
            } else if (partes[0].equals("Fuentes Apple")) {
                String fuentesApple = String.valueOf(partes[1]);
                jLabel20.setText(fuentesApple);
            } else if (partes[0].equals("GPU Apple")) {
                String gpuApple = String.valueOf(partes[1]);
                jLabel21.setText(gpuApple);
            } else if (partes[0].equals("PCN Apple")) {
                String pcnApple = String.valueOf(partes[1]);
                jLabel22.setText(pcnApple);
            } else if (partes[0].equals("PCGPU Apple")) {
                String pcgpuApple = String.valueOf(partes[1]);
                jLabel23.setText(pcgpuApple);
            } 
        }
        reader.close();
        System.out.println("Datos cargados exitosamente.");
    } catch (IOException e) {
        e.printStackTrace();
        System.out.println("Error al cargar los datos.");
    }
        
        
            try {
            BufferedReader reader = new BufferedReader(new FileReader("Datos MSI.txt"));
            String line;
            while ((line = reader.readLine()) != null) {
            String[] partes = line.split("=");
            if (partes[0].equals("Utilidad MSI")) {
                String utilidadMSI = String.valueOf(partes[1]);
                jLabel2.setText(utilidadMSI);
            }else if (partes[0].equals("Costo Operativo MSI")) {
                String costoMsi = String.valueOf(partes[1]);
                jLabel3.setText(costoMsi);
            } else if (partes[0].equals("Ganancias Brutas MSI")) {
                String gananciasMsi = String.valueOf(partes[1]);
                jLabel4.setText(gananciasMsi);
            } else if (partes[0].equals("Multas PM MSI")) {
                String multaMsi = String.valueOf(partes[1]);
                jLabel5.setText(multaMsi);
            } else if (partes[0].equals("CPU MSI")) {
                String cpuMSI = String.valueOf(partes[1]);
                jLabel6.setText(cpuMSI);
            } else if (partes[0].equals("Placas MSI")) {
                String placasMSI = String.valueOf(partes[1]);
                jLabel7.setText(placasMSI);
            } else if (partes[0].equals("RAM MSI")) {
                String ramMSI = String.valueOf(partes[1]);
                jLabel8.setText(ramMSI);
            } else if (partes[0].equals("Fuentes MSI")) {
                String fuentesMSI = String.valueOf(partes[1]);
                jLabel9.setText(fuentesMSI);
            } else if (partes[0].equals("GPU MSI")) {
                String gpuMSI = String.valueOf(partes[1]);
                jLabel10.setText(gpuMSI);
            } else if (partes[0].equals("PCN MSI")) {
                String pcnMSI = String.valueOf(partes[1]);
                jLabel11.setText(pcnMSI);
            } else if (partes[0].equals("PCGPU MSI")) {
                String pcgpuMSI = String.valueOf(partes[1]);
                jLabel12.setText(pcgpuMSI);
            }
            }
        reader.close();
        System.out.println("Datos cargados exitosamente.");
    } catch (IOException e) {
        e.printStackTrace();
        System.out.println("Error al cargar los datos.");
}

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estadisticas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
