/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Clases.Administrador;
import Clases.Empresa;
import Clases.ProjectManager;
import java.io.FileWriter;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;
//import org.jfree.chart.ChartFactory;
//import org.jfree.chart.ChartPanel;
//import org.jfree.chart.JFreeChart;
//import org.jfree.chart.plot.PlotOrientation;
//import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Windows 10
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CorrerSimulacion = new javax.swing.JButton();
        Estadisticas = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CorrerSimulacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CorrerSimulacion.setText("Correr simulacion");
        CorrerSimulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorrerSimulacionActionPerformed(evt);
            }
        });
        jPanel1.add(CorrerSimulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 170, 40));

        Estadisticas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Estadisticas.setText("Estadisticas");
        Estadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadisticasActionPerformed(evt);
            }
        });
        jPanel1.add(Estadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, 170, 40));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Cambiar parametros de la simulacion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 260, 40));

        jButton2.setText("Graficos utilidad/tiempo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, 170, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/22222.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadisticasActionPerformed
        // TODO add your handling code here:
        Estadisticas newframe = new Estadisticas();
        
        newframe.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_EstadisticasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Parametros newframe = new Parametros();
        
        newframe.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CorrerSimulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorrerSimulacionActionPerformed
        //Ejecuta a MSI
        Empresa msi = new Empresa("MSI", 180000, 25000, 3, 5, 2, 4, 6,  6, 4, 1, 4, 0.2, 2);
       ProjectManager pm = new ProjectManager(msi);
       Administrador admin = new Administrador( msi);
       msi.cargarMSI();
       msi.cargarTiempo();
       msi.crearProdCPU();
       msi.crearProdFuente();
       msi.crearProdGPU();
       msi.crearProdPlaca();
       msi.crearProdRAM();
       msi.crearEnsamblador();
       admin.start();
       pm.start();
       
       //Ejecuta a Apple
       Empresa apple = new Empresa("Apple", 150000, 120000, 4, 5, 6, 7, 8,  3, 2, 0.3, 2, 0.3, 3);
       ProjectManager pm1 = new ProjectManager(apple);
       Administrador admin1 = new Administrador( apple);
       apple.cargarApple();
       apple.cargarTiempo();
       apple.crearProdCPU();
       apple.crearProdFuente();
       apple.crearProdGPU();
       apple.crearProdPlaca();
       apple.crearProdRAM();
       apple.crearEnsamblador();
       admin1.start();
       pm1.start();
       
       
       try {
            sleep(msi.getMsPorDia() * msi.getDiasSim() + 15000);
        } catch (InterruptedException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       System.out.println("");
        System.out.println("*****************************************");
        System.out.println("INFO FINAL DE SIMULACION DE: "+msi.getNombre());
        System.out.println("El inventario de CPUs final es: " + msi.getAlmacen().getCantidadCPU());
        System.out.println("El inventario de RAMs final es: " + msi.getAlmacen().getCantidadRAM());
        System.out.println("El inventario de GPUs final es: " + msi.getAlmacen().getCantidadGPU());
        System.out.println("El inventario de Fuentes final es: " + msi.getAlmacen().getCantidadFuente());
        System.out.println("El inventario de Placas final es: " + msi.getAlmacen().getCantidadPlaca());  
        System.out.println("El inventario de Pc normales final es: " + msi.getAlmacen().getCantPc()); 
        System.out.println("El inventario de Pc con gpu final es: " + msi.getAlmacen().getCantPcGPU()); 
        System.out.println("");
        System.out.println("Total en multas para el Project Manager: "+msi.getMultaPm());
        System.out.println("");
        System.out.println("La ganancia final es de: "+msi.getGananciasBrutas());
        System.out.println("Las perdidas de la empresa fueron: "+msi.getCostoOperativo());
        System.out.println("La utilidad final es de: "+msi.getUtilidadEstudio());
        
        try {
            sleep(5000);
        } catch (InterruptedException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        System.out.println("");
        System.out.println("*****************************************");
        System.out.println("INFO FINAL DE SIMULACION DE: "+apple.getNombre());
        System.out.println("El inventario de CPUs final es: " + apple.getAlmacen().getCantidadCPU());
        System.out.println("El inventario de RAMs final es: " + apple.getAlmacen().getCantidadRAM());
        System.out.println("El inventario de GPUs final es: " + apple.getAlmacen().getCantidadGPU());
        System.out.println("El inventario de Fuentes final es: " + apple.getAlmacen().getCantidadFuente());
        System.out.println("El inventario de Placas final es: " + apple.getAlmacen().getCantidadPlaca());  
        System.out.println("El inventario de Pc normales final es: " + apple.getAlmacen().getCantPc()); 
        System.out.println("El inventario de Pc con gpu final es: " + apple.getAlmacen().getCantPcGPU()); 
        System.out.println("");
        System.out.println("Total en multas para el Project Manager: "+apple.getMultaPm());
        System.out.println("");
        System.out.println("La ganancia final es de: "+apple.getGananciasBrutas());
        System.out.println("Las perdidas de la empresa fueron: "+apple.getCostoOperativo());
        System.out.println("La utilidad final es de: "+apple.getUtilidadEstudio());
        
         try {
        FileWriter writer = new FileWriter("Datos.txt");
        writer.write("Utilidad Apple=" + apple.getUtilidadEstudio() + "\n");
        writer.write("Costo Operativo Apple=" +  apple.getCostoOperativo() + "\n");
        writer.write("Ganancias Brutas Apple=" +  apple.getGananciasBrutas() + "\n");
        writer.write("Multas PM Apple=" +  apple.getMultaPm() + "\n");
        writer.write("CPU Apple=" + apple.getAlmacen().getCantidadCPU() + "\n");
        writer.write("Placas Apple=" +  apple.getAlmacen().getCantidadPlaca() + "\n");
        writer.write("RAM Apple=" +  apple.getAlmacen().getCantidadRAM() + "\n");
        writer.write("Fuentes Apple=" +  apple.getAlmacen().getCantidadFuente() + "\n");
        writer.write("GPU Apple=" + apple.getAlmacen().getCantidadGPU() + "\n");
        writer.write("PCN Apple=" +  apple.getAlmacen().getCantPc() + "\n");
        writer.write("PCGPU Apple=" +  apple.getAlmacen().getCantPcGPU() + "\n");
        writer.write("Utilidad MSI=" + msi.getUtilidadEstudio() + "\n");
        writer.write("Costo Operativo MSI=" +  msi.getCostoOperativo() + "\n");
        writer.write("Ganancias Brutas MSI=" +  msi.getGananciasBrutas() + "\n");
        writer.write("Multas PM MSI=" +  msi.getMultaPm() + "\n");
        writer.write("CPU MSI=" + msi.getAlmacen().getCantidadCPU() + "\n");
        writer.write("Placa MSI=" +  msi.getAlmacen().getCantidadPlaca() + "\n");
        writer.write("RAM MSI=" +  msi.getAlmacen().getCantidadRAM() + "\n");
        writer.write("Fuentes MSI=" +  msi.getAlmacen().getCantidadFuente() + "\n");
        writer.write("GPU MSI=" + msi.getAlmacen().getCantidadGPU() + "\n");
        writer.write("PCN MSI=" +  msi.getAlmacen().getCantPc() + "\n");
        writer.write("PCGPU MSI=" +  msi.getAlmacen().getCantPcGPU() + "\n");
        writer.close();
        System.out.println("Datos guardados exitosamente.");
    } catch (IOException e) {
        e.printStackTrace();
        System.out.println("Error al guardar los datos.");
    }
        
    }//GEN-LAST:event_CorrerSimulacionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        Grafico newframe = new Grafico();
        
        newframe.setVisible(true);
        
        this.dispose();

        
    
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CorrerSimulacion;
    private javax.swing.JButton Estadisticas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
